[versions]
jackson = "3.2.0"
junit = "6.1.1"
springBoot = "4.1.0"
htmlunit = "5.3.0"

[libraries]
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "tools.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
htmlunit = { module = "org.htmlunit:htmlunit", version.ref = "htmlunit" }

[plugins]
java-gradle-plugin = { id = "java-gradle-plugin" }
java-library = { id = "java-library" }
