#!/usr/bin/env bash
# Runs the complete release gate, including samples, mutation verification, skill, and docs checks.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
gradle="${GRADLE_CMD:-$root/gradlew}"
junit_sample="$root/samples/junit-cart-orders"
spring_sample="$root/samples/spring-boot-cart-orders"

restore_sample() {
  local sample="$1"
  if [[ -f "$sample/.topplecat/escrow/manifest.json" && ! -d "$sample/src/hiddenTest" ]]; then
    "$gradle" -p "$sample" -q toppleCatRestore
  fi
}

cleanup() {
  local status=$?
  trap - EXIT
  set +e
  restore_sample "$junit_sample"
  restore_sample "$spring_sample"
  exit "$status"
}
trap cleanup EXIT

cd "$root"
if ! command -v python3 >/dev/null 2>&1; then
  echo "Release gate failed: python3 is required for scripts/verify-docs.py. Install Python 3 and rerun." >&2
  exit 1
fi
"$gradle" clean check
"$gradle" publishToMavenLocal
bash "$root/scripts/verify-toppletest-stage-dsl.sh"
"$gradle" -p "$junit_sample" help --task toppleCatInit

bash "$junit_sample/demo.sh"
bash "$spring_sample/demo.sh"
bash "$root/integration-tests/mutation-gate/verify.sh"

bash "$root/scripts/validate-skill.sh"
python3 "$root/scripts/verify-docs.py"

for artifact in \
  "$junit_sample/build/topplecat/evidence.json" \
  "$spring_sample/build/topplecat/evidence.json"; do
  grep -Fq '"PASS"' "$artifact"
  grep -Fq '"MUTATION"' "$artifact"
  grep -Fq '"DISABLED"' "$artifact"
  grep -Fq 'disabled by toppleCat.adversarial.mutation.enabled=false' "$artifact"
done

for feedback in \
  "$junit_sample/build/topplecat/agent-feedback.json" \
  "$spring_sample/build/topplecat/agent-feedback.json"; do
  if grep -Eiq 'coupon-hidden-800|\b800\b|customer-2|ReviewerBoundary|hiddenTest' "$feedback"; then
    echo "Private detail leaked into $feedback" >&2
    exit 1
  fi
done

for spec in \
  "$junit_sample/build/topplecat/reports/spec/index.html" \
  "$spring_sample/build/topplecat/reports/spec/index.html"; do
  if grep -Eiq 'coupon-hidden-800|\b800\b|customer-2|ReviewerBoundary|hiddenTest' "$spec"; then
    echo "Private detail leaked into $spec" >&2
    exit 1
  fi
done

restore_sample "$junit_sample"
"$gradle" -p "$junit_sample" toppleCatCheck

if [[ -e "$junit_sample/build/topplecat/reports/review/index.html" ]]; then
  echo "toppleCatCheck must not leave a reviewer HTML artifact" >&2
  exit 1
fi

"$gradle" -p "$junit_sample" toppleCatReview

junit_review="$junit_sample/build/topplecat/reports/review/data.json"
if [[ ! -f "$junit_review" ]]; then
  echo "Reviewer review was not generated by toppleCatReview" >&2
  exit 1
fi
if ! grep -Fq 'coupon-hidden-800' "$junit_review"; then
  echo "Reviewer review did not include the reviewer case" >&2
  exit 1
fi
if ! grep -Fq '套用優惠券並建立訂單' "$junit_review" || ! grep -Fq 'sourceCode' "$junit_review"; then
  echo "Reviewer review is missing static stage context or source fallback" >&2
  exit 1
fi

legacy_runtime="cu""cumber|gher""kin|topplecat-""cli|topplecat-""testkit"
residual="$(grep -R -nEI \
  --exclude-dir=build \
  --exclude-dir=.gradle \
  --exclude-dir=.topplecat \
  "$legacy_runtime" \
  topplecat-core \
  topplecat-junit \
  topplecat-report \
  topplecat-gradle-plugin \
  samples \
  integration-tests \
  scripts/verify-release.sh || true)"
if [[ -n "$residual" ]]; then
  echo "Legacy runtime or contract surface remains:" >&2
  printf '%s\n' "$residual" >&2
  exit 1
fi

echo "verify-release PASS"
