package io.github.samzhu.topplecat.report;

/**
 * Stable presentation reason that the offline renderer can localize without interpreting evidence.
 */
public enum VerificationSafeguardReason {
  CASE_FAILED,
  ALL_CASES_PASSED,
  NO_CASE_EVIDENCE,
  EXPECTED_COMPARISON_MISSING,
  EXPECTED_NOT_COMPARED,
  EXPECTED_COMPARISON_COMPLETED,
  NO_EXPECTED_RESULT,
  PROPERTY_COUNTEREXAMPLE,
  PROPERTY_EVIDENCE_INCOMPLETE,
  PROPERTY_COMPLETED,
  NO_PROPERTY,
  MUTATION_BASELINE_FAILED,
  MUTATION_EVIDENCE_UNAVAILABLE,
  NO_MUTATION_ATTRIBUTED,
  MUTATION_ATTRIBUTION_GAP,
  MUTATION_SURVIVED,
  MUTATION_DETECTED,
  GATE_RECORDED
}
